### PR TITLE
Tablemanager checkbox

### PR DESCRIPTION
**Pull request by tkcent**
Updated the tablemanager to now allow the checkbox type.  Multiple values can be selected and the values are stored in the database in a single field as json-encoded data.

### CODE REVIEW

**Comment by hsleisink** [comment]
Why use this construction and not multiple boolean types?

**Comment by tkcent** [comment]
If I understand the way the boolean types work, I would have to add an column to the table for every type.  If I had multiple tables using the same values (colors in this example) then I would have to manually add a new column to multiple times every time I added a new color.

I wanted to create a reference table that could be used by multiple tables and dynamically add new values without manual configuration (database changes, stylesheet changes, etc).

**Comment by hsleisink** [comment]
Yes, but the issue with this solution is that when I delete an entry from the color_type table, the dummy table may contain non-existing colors.

**Comment by tkcent** [comment]
Good point!  I was hoping to avoid having a separate table that holds the one (dummy) to many (color) relationship but that may be the best way. 

That would also solve the problem I have with storing the values as json data which is that the checkbox field is not searchable.  I will just have to add something similar to your foreignkey search solution.

**Comment by tkcent** [comment]
Let me know if you prefer a different way to share code.

**Pull request closed without merging**
